-- Arquivo: backend/src/main/resources/db/migration/V1__create_initial_tables.sql

-- 1. Nova Tabela: Tipo de Local
CREATE TABLE tipo_local (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

-- 2. Nova Tabela: Locais de Trabalho
CREATE TABLE locais_trabalho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    tipo_local_id BIGINT NOT NULL,

    CONSTRAINT fk_local_tipo
        FOREIGN KEY(tipo_local_id)
        REFERENCES tipo_local(id)
);

-- 3. Tabela de Funcionários ATUALIZADA
CREATE TABLE funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    celular VARCHAR(20) NOT NULL,
    local_trabalho_id BIGINT NOT NULL, -- Campo 'obra' substituído

    CONSTRAINT fk_funcionario_local
        FOREIGN KEY(local_trabalho_id)
        REFERENCES locais_trabalho(id)
);

-- Tabela de Conteúdos (Sem alteração)
CREATE TABLE conteudos_dds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(120) NOT NULL,
    descricao VARCHAR(2000) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    url VARCHAR(1000),
    arquivo_nome VARCHAR(255),
    arquivo_path VARCHAR(1000)
);

-- Tabela de Envios (Sem alteração estrutural)
CREATE TABLE envios_dds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id BIGINT NOT NULL,
    conteudo_id BIGINT NOT NULL,
    data_envio DATE NOT NULL,
    momento_envio TIMESTAMP NOT NULL,
    momento_confirmacao TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    token_acesso VARCHAR(64) NOT NULL UNIQUE,

    CONSTRAINT fk_envio_funcionario
        FOREIGN KEY(funcionario_id)
        REFERENCES funcionarios(id),

    CONSTRAINT fk_envio_conteudo
        FOREIGN KEY(conteudo_id)
        REFERENCES conteudos_dds(id)
);

-- Índices
CREATE INDEX idx_envio_data_envio ON envios_dds(data_envio);
CREATE INDEX idx_envio_token_acesso ON envios_dds(token_acesso);
CREATE INDEX idx_funcionario_local_id ON funcionarios(local_trabalho_id);
CREATE INDEX idx_local_tipo_id ON locais_trabalho(tipo_local_id);
