-- Arquivo: backend/src/main/resources/db/migration/V4__criar_estrutura_corporativa.sql

CREATE TABLE empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(200) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    tenant_slug VARCHAR(120) NOT NULL UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO empresas (id, razao_social, cnpj, tenant_slug, ativo)
VALUES (1, 'Empresa Padrão', '00000000000000', 'empresa-padrao', TRUE)
ON CONFLICT DO NOTHING;

ALTER TABLE empresas ALTER COLUMN id RESTART WITH 2;

ALTER TABLE locais_trabalho
    ADD CONSTRAINT fk_locais_trabalho_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresas(id);

ALTER TABLE funcionarios
    ADD CONSTRAINT fk_funcionarios_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresas(id);

ALTER TABLE conteudos_dds
    ADD CONSTRAINT fk_conteudos_dds_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresas(id);

ALTER TABLE envios_dds
    ADD CONSTRAINT fk_envios_dds_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES empresas(id);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    senha_hash VARCHAR(120) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_usuarios_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

INSERT INTO usuarios (empresa_id, nome, email, senha_hash, perfil)
VALUES (
    1,
    'Administrador DDS Fácil',
    'admin@ddsfacil.com',
    '$2b$12$3St3lAhB/db7LmGFkN30B.pcsQBvzeAwSaf8GnroQ.x3.IstkcqKu',
    'ADMIN'
);

CREATE TABLE licencas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL UNIQUE,
    tipo_plano VARCHAR(40) NOT NULL,
    saldo_sms INTEGER NOT NULL DEFAULT 0,
    saldo_whatsapp INTEGER NOT NULL DEFAULT 0,
    data_renovacao DATE,
    status_pagamento VARCHAR(20) NOT NULL DEFAULT 'EM_DIA',
    atualizado_em TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_licencas_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id)
);

INSERT INTO licencas (empresa_id, tipo_plano, saldo_sms, saldo_whatsapp, data_renovacao, status_pagamento)
VALUES (1, 'PRO', 50, 0, CURRENT_DATE + INTERVAL '30 days', 'EM_DIA');

ALTER TABLE envios_dds
    ADD COLUMN erro_entrega VARCHAR(500);
