-- Arquivo: backend/src/main/resources/db/migration/V5__criar_tokens_redefinicao_senha.sql

CREATE TABLE tokens_redefinicao_senha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    token VARCHAR(120) NOT NULL UNIQUE,
    expira_em TIMESTAMP NOT NULL,
    usado BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_token_reset_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
);

CREATE INDEX idx_token_reset_token ON tokens_redefinicao_senha(token);
